model:
  name: 'embedding_classifier'
  predict_full_image: true
  embedding_aggregate: mean
  class_aggregate: min
  distance_metric: euclidean

  # define embedding model below
  model:
    name: 'embedding_vit'
    weights_file:  'data/application_data/model_data/SimpleEmbeddingModel_weights.h5'
    input_size: [640, 640]
    embedding_size: 256
    backbone: vit_b32
